"""Add mymodel

Revision ID: 3ba8b42ca58c
Revises: 06a04cc084c6
Create Date: 2019-04-30 12:14:14.470912

"""

# revision identifiers, used by Alembic.
revision = '3ba8b42ca58c'
down_revision = '06a04cc084c6'
branch_labels = None
depends_on = None

import datetime
import websauna.system.model.columns
from sqlalchemy.types import Text  # Needed from proper creation of JSON fields as Alembic inserts astext_type=Text() row

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mymodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mymodel'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mymodel')
    # ### end Alembic commands ###

